### ISSUE TITLE
Add an API key-based connection class

### ISSUE THREAD

**Issue by thepolytheist** [Ruby-Octopus/ruby-octopus#3]
There should be a basic Octopus server connection class that takes in a server URL and credentials. This will generate a new Faraday base connection that can be used to make API requests in the future.

If we want to add a model class for testing, we should pick something simple and consistent between servers, like Environments. Projects are also a candidate, however I believe that model is slightly more complicated. Tenants are familiar, but they're an optional feature of the server, so they aren't as critical.

**Comment by Merckinator** [comment]
Why do we need a base connection class? The end user surely won't be instantiating it, so won't a Octopus Client class just be creating it behind the scenes when it is instantiated?

Basically, what's the added benefit to this being its own class, instead of just being a Faraday connection object?

**Comment by thepolytheist** [comment]
For extensibility, it's possible that the end user _will_ be instantiating it. I don't have any particular use cases in mind, but I don't see why they wouldn't be allowed to.

My preference for it being its own class that wraps the Faraday connection rather than just a Faraday connection itself is because just using a raw Faraday connection tightly couples the project to the Faraday connection API. Wrapping it allows us to define the interface to make requests.
